---
- name: Prepare localhost environment to setup openshift cluster
  hosts: localhost
  tasks:
    - name: Ensure group_vars folder exists
      file:
        path: /etc/ansible/group_vars
        recurse: true
        state: directory
      tags:
        - pre_tasks
        - setup_fact
        - inventory

    - name: Generate inventory file
      template:
        src: hosts.j2
        dest: /etc/ansible/hosts
      tags:
        - pre_tasks
        - setup_fact
        - inventory

    - name: Generate inventory file
      template:
        src: OSEv3
        dest: /etc/ansible/group_vars/OSEv3
      tags:
        - pre_tasks
        - setup_fact
        - inventory

    - name: Re run setup to use custom facts
      setup: ~
      tags:
        - pre_tasks
        - setup_fact

    - meta: refresh_inventory
      tags:
        - pre_tasks
        - setup_fact
        - inventory

- name: Prepare GUID environment variable across all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: if [ "X$GUID" != "X$(hostname | cut -d"." -f2)" ]; then export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc; fi
      tags:
        - pre_tasks

- name: Verify Installation and Configuration of Docker
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl restart docker
      tags:
      - dockerrestart


- name: Verify NFS Shared Volumes on Hosts
  hosts: nfs
  tasks:
  - name: Check NFS server
    shell: exportfs
    tags:
      - nfs


- name: Install packages and config auth
  hosts: localhost
  tasks:
    - name: required packages are present
      yum:
        name:
          - atomic-openshift-clients
          - openshift-ansible
        state: present
      tags:
        - pre_tasks
        - packages

#- name: Generate Inventory Hosts File
#  hosts: localhost
#  tasks:
#    - name: Generate Inventory script
#      script: scripts/generate_inventory.sh

- name: Execute the openshift-ansible prerequisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  tags:
    - install_ocp
    - install_pre

- name: Execute the openshift-ansible Deployer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
  tags:
    - install_ocp

- name: Verify OpenShift Cluster
  hosts: masters[0]
  tasks:
    - name: copy the .kube directory from master1 to your bastion
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: true
      tags:
        - post_install

- name: Verify OpenShift Cluster
  hosts: masters
  tasks:
    - name: Add user Openshift Cluster
      shell: htpasswd -b /etc/origin/master/htpasswd admin r3dh4t1!
      tags:
        - post_install

- name: Post installation configuration
  hosts: localhost
  tasks:
    - name: make sure you are system:dmin
      shell: oc whoami | grep system:admin
      tags:
        - post_install
    - name: Add cluster-admin policy to user
      shell: oc adm policy add-cluster-role-to-user cluster-admin admin
      tags:
        - post_install

- name: Create PVs for Users
  hosts: nfs
  tasks:
    - name:
      script: scripts/create_pvs.sh
    - name: Restarting NFS Server...
      shell: systemctl restart nfs-server
      tags:
        - nfs


- name: Create 25 definitions files for PVs 5G size
  hosts: localhost
  tasks:
    - name: Running for 5GB
      script: scripts/pvs_5Gsize.sh
      tags:
        - nfs

- name: Create 25 definitions files for PVs 10G size
  hosts: localhost
  tasks:
    - name: Running for 10GB
      script: scripts/pvs_10Gsize.sh
      tags:
        - nfs

- name: Create all PVs from definitions files
  hosts: localhost
  tasks:
    - name: "Creating PVs from the files.."
      shell: "cat /root/pvs/* | oc create -f -"
      tags:
        - nfs

- name: Fix NFS Persistent Volume Recycling
  hosts: nodes
  tasks:
    - name: "pull the recycler image"
      shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest
    - name: "tag the recycler image for specific version"
      shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.11.43
  tags:
    - fixnfs
    - nfs

- name: Jenkins Setup
  hosts: localhost
  tasks:
    - name: jenkins setup
      script: scripts/nodejs_mongo_app.sh
      tags:
        - jenkins

#- name: HPA configuration on production deployment of openshift-tasks
#  hosts: localhost
#  tasks: scripts/nodejs_mongo_app.sh is having the HPA command. 

- name: Creation of users for Alpha and Beta clients
  hosts: localhost
  tasks:
    - name: Multitenancy Script
      script: scripts/multitenancy.sh
      tags:
        - multitenancy

- name: Creation of users for Alpha and Beta clients
  hosts: masters
  tasks:
    - name: Restart atomic-openshift-node
      shell: systemctl restart atomic-openshift-node
    - name: Restart API
      shell:  /usr/local/bin/master-restart api 
    - name: Restart Controller
      shell: /usr/local/bin/master-restart controllers 
      tags:
        - multitenancy
        - restartapi

- name: Creation of projects for Alpha and Beta clients
  hosts: localhost
  tasks:
    - name: Create alpha project
      shell: oc new-project alpha --display-name='Alpha Corp'
    - name: Set node-selector for alpha project
      shell: oc patch namespace alpha -p '{"metadata":{"annotations":{"openshift.io/node-selector":"client=alpha"}}}'
    - name: Create beta project
      shell: oc new-project beta --display-name='Beta Corp'
    - name: Set node-selector for beta project
      shell: oc patch namespace beta -p '{"metadata":{"annotations":{"openshift.io/node-selector":"client=beta"}}}'
    - name: Create common project
      shell: oc new-project common --display-name='Common Corp'
    - name: Set node-selector for common project
      shell: oc patch namespace common -p '{"metadata":{"annotations":{"openshift.io/node-selector":"client=common"}}}'
  tags:
    - multitenancy
    - create-project

- name: Assigning labels to the users according to its group
  hosts: localhost
  tasks:
    - name: Adding user labels 
      shell: scripts/set_labels.sh
    - name: Adding alpha-grp to alpha project
      shell: oc adm policy add-role-to-group admin alpha-grp -n alpha
    - name: Adding beta-grp to beta project
      shell: oc adm policy add-role-to-group admin beta-grp -n beta
  tags:
    - multitenancy
    - user-labels


- name: Setup the environment for Alpha and Beta clients
  hosts: localhost
  tasks:
    - name: Adding node1 labels
      shell: oc label node node1.8b7c.internal client=alpha
    - name: Adding node2 labels
      shell: oc label node node2.8b7c.internal client=common
    - name: Adding node3 labels
      shell: oc label node node3.8b7c.internal client=beta
    - name: Adding node4 labels
      shell: oc label node node4.8b7c.internal client=common
  tags:
    - multitenancy
    - node-labels
