apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-build
    creationTimestam: null
  displayName: Spring Rest App - Build
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-dev
    creationTimestam: null
  displayName: Spring Rest App - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-test
    creationTimestam: null
  displayName: Spring Rest App - Test
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-prod
    creationTimestam: null
  displayName: Spring Rest App - Prod
